# Generated by Django 2.2 on 2020-10-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeelitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeelItem',
            new_name='ProfileFeedItem',
        ),
    ]
